2.7.15 - Fix push notification

diff --git a/bin/apk b/bin/apk
--- a/bin/apk
+++ b/bin/apk
@@ -7,7 +7,7 @@
 #
 # $ ./bin/apk [company] [appname] [version]
 # Example:
-# $ ./bin/apk agenciafoccus Photogram 3.0.2
+# $ ./bin/apk agenciafoccus Photogram 2.7.14 ../../agfoccus.keystore
 #
 #
 # Original at https://gist.github.com/th3m4ri0/acc2003adc7dffdbbad6
@@ -15,12 +15,15 @@
 #
 # Features : Willian Ribeiro Angelo<agfoccus@gmail.com>
 
+# keytool -exportcert -list -v -alias [alias] -keystore [yourkey.keystore]
+
 # Abort if any command returns something else than 0
 set -e
 
 company="$1"
 appname="$2"
 version="$3"
+keystore="$4"
 
 if [[ -z "$1" ]]; then
     echo "No company name provided, aborting..."
@@ -33,6 +36,11 @@ fi
 
 if [[ -z "$3" ]]; then
     echo "No version provided, aborting..."
+    exit 1
+fi
+
+if [[ -z "$4" ]]; then
+    echo "No keystore, aborting..."
     exit 1
 fi
 
@@ -50,9 +58,12 @@ echo ""
 echo ""
 echo "---> Zipaligning"
 
-mkdir -p releases/
-./zipalign -v 4 platforms/android/build/outputs/apk/android-release.apk releases/com.$company.$appname.v$version.apk
+apksigner sign --ks [chave.keystore] build.apk
 
+mkdir -p releases/
+./zipalign -v -p 4 platforms/android/build/outputs/apk/android-release.apk releases/com.$company.$appname.v$version.apk
+/usr/local/Cellar/android-sdk/24.4.1_1/build-tools/25.0.2/apksigner sign --ks $keystore releases/com.$company.$appname.v$version.apk
+/usr/local/Cellar/android-sdk/24.4.1_1/build-tools/25.0.2/apksigner verify --verbose releases/com.$company.$appname.v$version.apk
 
 echo ""
 echo ""
